select
    asset_management_fees_none as revenue_assetmanagement,
    basic_earnings_per_share_none as revenue_basicearningspershare,
    card_income_none as revenue_cardincome,
    commissions_and_other_fees_none as revenue_commissions,
    compensation_expense_none as expense_compensation,
    effective_income_tax_rate_none || '%' as incometaxrate,
    income_tax_expense_none as expense_incometax,
    interest_expense_none as expense_interest,
    interest_income_none as revenue_interest,
    investment_banking_fees_none as revenue_investmentbanking,
    investment_securities_losses_none as revenue_investmentsecuritieslosses,
    lending__and_deposit_related_fees_none as expense_lendingdeposit,
    marketing_none as expense_marketing,
    mortgage_fees_and_related_income_none as revenue_mortgage,
    none_income_before_income_tax_expense as expense_incometax,
    none_net_income as expense_netincome,
    none_net_interest_income as revenue_netinterest,
    none_noninterest_revenue as revenue_noninterest,
    none_total_net_revenue as totalnetrevenue,
    none_total_noninterest_expense as totalnetexpense,
    occupancy_expense_none as expense_occupancy,
    other_expense__a__none as expense_other,
    other_income_none revenue_otherincome,
    overhead_ratio_none || '%' as overheadratio,
    principal_transactions_none as revenue_principaltransactions,
    professional_and_outside_services_none as expense_professionalservices,
    provision_for_credit_losses_none as revenue_provisionlosses,
    return_on_assets__b__none || '%' as returnon_assets,
    return_on_common_equity__b__none as returnon_commonequity,
    return_on_tangible_common_equity__b_c__none || '%' as returnon_tangiblecommonequity,
    revenue_none as quarters,
    technology__communications_and_equipment_expense_none as expense_equipment
from {{ source("raw_data_source", "CONSOLIDATED_STATEMENTS_OF_INCOME") }}
