SELECT
    AGGREGATE_REPURCHASES_OF_COMMON_STOCK_NONE AS AggregateRepurchase_Commonstock,
    AVERAGE_PRICE_PAID_PER_SHARE_OF_COMMON_STOCK_NONE AS AvgPricePaidPerShare_Commonstock,
    CASH_DIVIDENDS_DECLARED_PER_SHARE_NONE,
    DIVIDEND_PAYOUT_RATIO_NONE,
    NONE_LESS__PREFERRED_STOCK_DIVIDENDS,
    NONE_NET_INCOME,
    NONE_NET_INCOME_APPLICABLE_TO_COMMON_EQUITY,
    NONE_NET_INCOME_APPLICABLE_TO_COMMON_STOCKHOLDERS AS Basic_NetIncomeToCOmmonStockHolders_EarningPerShares,
    NONE_NET_INCOME_APPLICABLE_TO_COMMON_STOCKHOLDERS ,
    NONE_NET_INCOME_PER_SHARE,
    NONE_NET_INCOME_PER_SHARE_1,
    NONE_NONE AS Quarters,
    NONE_PARTICIPATING_SECURITIES,
    NONE_PURCHASE_PLANS,
    NONE_TOTAL_WEIGHTED_AVERAGE_BASIC_SHARES_OUTSTANDING_1,
    NONE_TOTAL_WEIGHTED_AVERAGE_DILUTED_SHARES_OUTSTANDING,
    NONE__RSUS__AND_STOCK_APPRECIATION_RIGHTS__SARS_,
    TOTAL_SHARES_OF_COMMON_STOCK_REPURCHASED_NONE AS TotalShares_Commonstock
FROM {{ source("raw_data_source", "EARNINGS_PER_SHARE_AND_RELATED_INFORMATION") }}

